name: Build Citizens

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "github.actor != 'dependabot[bot]'"
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Download the CraftBukkit jar
      - name: Download CraftBukkit jar
        run: wget https://cdn.getbukkit.org/craftbukkit/craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar -O ./craftbukkit-1.8.8-R0.1-SNAPSHOT.jar

      # Manually install CraftBukkit into the local Maven repository
      - name: Install CraftBukkit in local repo
        run: |
          mvn install:install-file \
          -Dfile=./craftbukkit-1.8.8-R0.1-SNAPSHOT.jar \
          -DgroupId=org.bukkit \
          -DartifactId=craftbukkit \
          -Dversion=1.8.8-R0.1-SNAPSHOT \
          -Dpackaging=jar

      - name: Build
        run: mvn -V -B clean package --file pom.xml

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Plugin JAR
          path: target/*.jar
          if-no-files-found: error
